apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kong-psql-volume
  labels:
    type: local
    app: kong-psql
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kong-psql-claim
  labels:
    app: kong-psql
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  volumeName: pv-kong-psql-volume
